bothan-binance/src/service.rs, bothan-binance/src/service/builder.rs, bothan-kraken/examples/kraken_basic.rs, bothan-kraken/src/lib.rs, bothan-kraken/src/service.rs, bothan-kraken/src/service/builder.rs
=> [fix] Patch Websocket Sources

.dockerignore, Cargo.toml, bothan-api-proxy/.dockerignore, bothan-api/server/.dockerignore, bothan-api/server/Cargo.toml, bothan-api/server/Dockerfile, bothan-api/server/config.toml.example, bothan-api/server/src/api.rs, bothan-api/server/src/config.rs, bothan-api/server/src/main.rs, bothan-api/server/src/manager/price_service/manager.rs, bothan-api/server/src/tasks/signal_task.rs, bothan-binance/src/service.rs, bothan-binance/src/service/builder.rs, bothan-core/src/cache/hashmap.rs, bothan-cryptocompare/src/service.rs, bothan-kraken/src/service/builder.rs
=> [fix] Add Logging and Minor Fixes

Cargo.toml, bothan-coinbase/Cargo.toml, bothan-coinbase/examples/coinbase_basic.rs, bothan-coinbase/src/api.rs, bothan-coinbase/src/api/error.rs, bothan-coinbase/src/api/types.rs, bothan-coinbase/src/api/types/channels.rs, bothan-coinbase/src/api/types/channels/ticker.rs, bothan-coinbase/src/api/types/request.rs, bothan-coinbase/src/api/websocket.rs, bothan-coinbase/src/error.rs, bothan-coinbase/src/lib.rs, bothan-coinbase/src/service.rs, bothan-coinbase/src/service/builder.rs, bothan-coinbase/src/types.rs
=> [feat] Add Coinbase

.github/workflows/ci.yml, bothan-api/server/Cargo.toml, bothan-api/server/src/api.rs, bothan-api/server/src/lib.rs, bothan-api/server/src/main.rs, bothan-api/server/src/manager.rs, bothan-api/server/src/manager/price_service/manager.rs, bothan-api/server/src/registry.rs, bothan-api/server/src/utils.rs, bothan-api/server/tests/registry_test.rs
=> [feat] Add Registry Validation

bothan-api-proxy/main.go
=> [fix] Patch Proxy

Cargo.toml, bothan-core/Cargo.toml
=> [chore] Update Core Cargo

Cargo.lock, Cargo.toml, bothan-coinmarketcap/Cargo.toml, bothan-coinmarketcap/examples/coinmarketcap_basic.rs, bothan-coinmarketcap/src/api/builder.rs, bothan-coinmarketcap/src/api/error.rs, bothan-coinmarketcap/src/api/rest.rs, bothan-coinmarketcap/src/lib.rs, bothan-coinmarketcap/src/worker.rs, bothan-coinmarketcap/src/worker/asset_worker.rs, bothan-coinmarketcap/src/worker/builder.rs, bothan-coinmarketcap/src/worker/error.rs, bothan-coinmarketcap/src/worker/opts.rs, bothan-coinmarketcap/src/worker/types.rs
=> [chore ] Refactor CoinMarketCap

.github/workflows/upload_binary.yml
=> [feat] Add Binary CI

bothan-coingecko/src/worker/opts.rs, docs/setup_bothan.md
=> [chore] Add Startup Docs

bothan-api/server-cli/config.example.toml
=> [chore] Add Example Config

bothan-api/server/src/api/utils.rs
=> [!fix] Fix Scaling Bug

Cargo.lock, bothan-api/server-cli/Cargo.toml, bothan-api/server/Cargo.toml, bothan-binance/Cargo.toml, bothan-bybit/Cargo.toml, bothan-coinbase/Cargo.toml, bothan-coingecko/Cargo.toml, bothan-coinmarketcap/Cargo.toml, bothan-core/Cargo.toml, bothan-cryptocompare/Cargo.toml, bothan-htx/Cargo.toml, bothan-kraken/Cargo.toml, bothan-okx/Cargo.toml
=> [chore] update version to 0.0.1-alpha.4

bothan-core/src/manager/crypto_asset_info/error.rs, bothan-core/src/manager/crypto_asset_info/manager.rs, bothan-core/src/manager/crypto_asset_info/price/cache.rs, bothan-core/src/manager/crypto_asset_info/price/error.rs, bothan-core/src/manager/crypto_asset_info/price/tasks.rs, bothan-core/src/manager/crypto_asset_info/signal_ids.rs, bothan-core/src/monitoring/records.rs, bothan-core/src/registry.rs, bothan-core/src/registry/validate.rs, bothan-core/src/store.rs, bothan-core/src/store/manager.rs, bothan-core/src/store/types.rs
=> [feat] Add Unit Tests to bothan-core

bothan-api/server/src/lib.rs
=> [fix] Fix Semver

bothan-api/server-cli/src/commands/start.rs, bothan-core/src/manager/crypto_asset_info/price/tasks.rs
=> [fix] Fix Bugs

bothan-bybit/src/api/types.rs, bothan-bybit/src/worker/asset_worker.rs, bothan-bybit/src/worker/builder.rs, bothan-bybit/src/worker/error.rs, bothan-coinbase/src/worker/builder.rs, bothan-coinbase/src/worker/error.rs, bothan-htx/src/worker/asset_worker.rs, bothan-htx/src/worker/builder.rs, bothan-htx/src/worker/error.rs, bothan-kraken/src/worker/builder.rs, bothan-kraken/src/worker/error.rs, bothan-okx/src/worker/builder.rs, bothan-okx/src/worker/error.rs
=> [fix] Bug Fixes

bothan-binance/src/worker/asset_worker.rs, bothan-core/src/manager/crypto_asset_info/price/tasks.rs, bothan-core/src/manager/crypto_asset_info/types.rs, bothan-core/src/monitoring/records.rs, bothan-core/src/worker.rs
=> [feat] Add Asset State to Monitoring

bothan-binance/src/worker/asset_worker.rs, bothan-core/src/manager/crypto_asset_info/price/tasks.rs, bothan-core/src/manager/crypto_asset_info/types.rs, bothan-core/src/monitoring/records.rs, bothan-core/src/registry/post_processor.rs, bothan-core/src/registry/post_processor/tick.rs, bothan-core/src/registry/processor.rs, bothan-core/src/registry/processor/median.rs, bothan-core/src/registry/processor/weighted_median.rs, bothan-core/src/worker.rs, proto/bothan/v1/bothan.proto
=> [feat] Add Monitoring Details

bothan-core/src/monitoring/client.rs, bothan-core/src/monitoring/types.rs
=> [chore] Update Monitoring

bothan-lib/Cargo.toml
=> [chore] Add Description to Cargo.toml

Cargo.toml, bothan-api/client/rust-client/Cargo.toml, bothan-binance/Cargo.toml, bothan-bitfinex/Cargo.toml, bothan-bybit/Cargo.toml, bothan-coinbase/Cargo.toml, bothan-coingecko/Cargo.toml, bothan-coinmarketcap/Cargo.toml, bothan-htx/Cargo.toml, bothan-kraken/Cargo.toml, bothan-lib/Cargo.toml, bothan-okx/Cargo.toml
=> [chore] Add Descriptions to Cargo.toml

bothan-core/src/manager/crypto_asset_info/manager.rs
- Changed get_info to show successfully enabled sources that are actively getting data rather than just enabled sources
=> [feat] Update GetInfo Path

Cargo.lock, bothan-api/server-cli/Cargo.toml, bothan-api/server-cli/src/commands.rs, bothan-api/server-cli/src/commands/query.rs, bothan-api/server-cli/src/main.rs
Add new command for Bothan to be able to query prices for each source ex. `bothan query binance btcusdt`
=> [feat] cmd for query prices on each sources

Cargo.lock, Cargo.toml, bothan-api/client/rust-client/Cargo.toml, bothan-api/server-cli/Cargo.toml, bothan-api/server/Cargo.toml, bothan-binance/Cargo.toml, bothan-bitfinex/Cargo.toml, bothan-bybit/Cargo.toml, bothan-coinbase/Cargo.toml, bothan-coingecko/Cargo.toml, bothan-coinmarketcap/Cargo.toml, bothan-core/Cargo.toml, bothan-core/src/manager/crypto_asset_info/manager.rs, bothan-htx/Cargo.toml, bothan-kraken/Cargo.toml, bothan-lib/Cargo.toml, bothan-okx/Cargo.toml
- change beta.2 to beta.3
- fix post-heartbeat logic
=> [feat] patch version

bothan-api/client/rust-client/src/client/rest.rs
=> [Fix] Add signal_ids to push monitoring records rest path

bothan-coinbase/src/api/types.rs, bothan-coinbase/src/api/types/request.rs, bothan-coinbase/src/api/websocket.rs, bothan-htx/src/api/types.rs, bothan-htx/src/api/websocket.rs
- add response type `Error` for source coinbase and htx
- add warning when receiving Error response
=> [Fix] Add error response type for sources

bothan-coingecko/src/api.rs, bothan-coingecko/src/api/builder.rs, bothan-coingecko/src/api/error.rs, bothan-coingecko/src/api/rest.rs, bothan-coingecko/src/api/types.rs, bothan-coingecko/src/worker.rs, bothan-coingecko/src/worker/opts.rs
- Add CoinGecko doc for Bothan
=> [Feat] Add CoinGecko Doc

bothan-bitfinex/src/api.rs, bothan-bitfinex/src/api/builder.rs, bothan-bitfinex/src/api/error.rs, bothan-bitfinex/src/api/msg.rs, bothan-bitfinex/src/api/msg/ticker.rs, bothan-bitfinex/src/api/msg/ticker/funding.rs, bothan-bitfinex/src/api/msg/ticker/spot.rs, bothan-bitfinex/src/api/rest.rs, bothan-bitfinex/src/worker.rs, bothan-bitfinex/src/worker/opts.rs
=> [Feat] Add Bitfinex doc

Cargo.lock, Cargo.toml, bothan-api/client/rust-client/Cargo.toml, bothan-api/server-cli/Cargo.toml, bothan-api/server/Cargo.toml, bothan-binance/Cargo.toml, bothan-bitfinex/Cargo.toml, bothan-bybit/Cargo.toml, bothan-coinbase/Cargo.toml, bothan-coingecko/Cargo.toml, bothan-coinmarketcap/Cargo.toml, bothan-core/Cargo.toml, bothan-htx/Cargo.toml, bothan-kraken/Cargo.toml, bothan-lib/Cargo.toml, bothan-okx/Cargo.toml
- Change crate version from 0.0.1-beta-3 to 0.0.1
=> [Feat] update crate version

bothan-lib/src/metrics.rs, bothan-lib/src/metrics/rest.rs, bothan-lib/src/metrics/server.rs, bothan-lib/src/metrics/store.rs, bothan-lib/src/metrics/utils.rs, bothan-lib/src/metrics/websocket.rs, bothan-lib/src/registry/validate.rs
=> [Feat] add metrics doc
